name: DFM Switch

on: [push]

jobs:
  switch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          if grep -q "dfm=true" dfm.txt; then
            cp dfm.html index.html
          else
            cp site.html index.html
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
