name: DFM Switch

on: [push]

jobs:
  switch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          curl -s https://raw.githubusercontent.com/ixviPCs/dev.ixvipcs.com/main/dfm.txt > dfm_remote.txt

          if grep -q "dfm=true" dfm_remote.txt; then
            cp dfm.html index.html
          else
            cp site.html index.html
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
